#!/bin/busybox sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs devtmpfs /dev

echo "falg" > /flag

echo "--- Minimal Kernel Pwn Environment ---"
dmesg | grep -v "clocksource"

exec /bin/sh
